"""add leve language user

Revision ID: 1b3adea8110c
Revises: c4ec25935b27
Create Date: 2026-03-10 11:30:49.099310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3adea8110c'
down_revision: Union[str, Sequence[str], None] = 'c4ec25935b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_language', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_language', 'level')
    # ### end Alembic commands ###
