"""add user_id to project and contact

Revision ID: 9d805f35537c
Revises: 8e166461c07b
Create Date: 2026-03-02 16:33:03.043517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d805f35537c'
down_revision: Union[str, Sequence[str], None] = '8e166461c07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contact', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'Contact', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Contact', type_='foreignkey')
    op.drop_column('Contact', 'user_id')
    # ### end Alembic commands ###
