"""add user image and description

Revision ID: c4ec25935b27
Revises: 4b1569ecbb1c
Create Date: 2026-03-06 19:21:06.200630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ec25935b27'
down_revision: Union[str, Sequence[str], None] = '4b1569ecbb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('description', sa.String(), nullable=True))
    op.add_column('User', sa.Column('user_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'user_image')
    op.drop_column('User', 'description')
    # ### end Alembic commands ###
