"""add user_id to project

Revision ID: cae50c384479
Revises: e54419c5814e
Create Date: 2026-03-02 16:16:54.778024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae50c384479'
down_revision: Union[str, Sequence[str], None] = 'e54419c5814e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'Project', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Project', type_='foreignkey')
    op.drop_column('Project', 'user_id')
    # ### end Alembic commands ###
