"""initial tables

Revision ID: cb7876c4c2a3
Revises: 
Create Date: 2026-02-25 11:28:10.094499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7876c4c2a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Language',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('repository_link', sa.String(), nullable=True),
    sa.Column('deploy_link', sa.String(), nullable=True),
    sa.Column('image_link', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Stack',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name1', sa.String(), nullable=True),
    sa.Column('last_name2', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('User_language',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['Language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'language_id')
    )
    op.create_table('User_stack',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stack_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['Stack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stack_id')
    )
    op.drop_table('prueba_remota')
    op.drop_table('prueba')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('prueba_remota',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('User_stack')
    op.drop_table('User_language')
    op.drop_table('User')
    op.drop_table('Stack')
    op.drop_table('Project')
    op.drop_table('Language')
    op.drop_table('Contact')
    # ### end Alembic commands ###
