"""add auditory user language

Revision ID: d4bed074ec76
Revises: 1b3adea8110c
Create Date: 2026-03-10 11:34:04.518897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4bed074ec76'
down_revision: Union[str, Sequence[str], None] = '1b3adea8110c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_language', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('User_language', sa.Column('updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_language', 'updated_at')
    op.drop_column('User_language', 'created_at')
    # ### end Alembic commands ###
