"""status_models

Revision ID: e54419c5814e
Revises: f226b290b2ce
Create Date: 2026-02-27 11:53:46.819284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54419c5814e'
down_revision: Union[str, Sequence[str], None] = 'f226b290b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Primero agregamos columnas status
    op.add_column('Contact', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('Language', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('Project', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('Stack', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('User_language', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('User_stack', sa.Column('status', sa.Boolean(), nullable=True))

    # Eliminamos foreign keys antes de cambiar tipos
    op.drop_constraint('User_language_language_id_fkey', 'User_language', type_='foreignkey')
    op.drop_constraint('User_language_user_id_fkey', 'User_language', type_='foreignkey')
    op.drop_constraint('User_stack_user_id_fkey', 'User_stack', type_='foreignkey')
    op.drop_constraint('User_stack_stack_id_fkey', 'User_stack', type_='foreignkey')

    # Cambiamos columnas de tablas hijas primero
    op.alter_column('User_language', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.alter_column('User_language', 'language_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='language_id::uuid')
    op.alter_column('User_stack', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.alter_column('User_stack', 'stack_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='stack_id::uuid')

    # Luego cambiamos las tablas padre
    op.alter_column('Contact', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('Language', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('Project', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('Stack', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('User', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')

    # Recreamos las foreign keys con los tipos correctos
    op.create_foreign_key(None, 'User_language', 'User', ['user_id'], ['id'])
    op.create_foreign_key(None, 'User_language', 'Language', ['language_id'], ['id'])
    op.create_foreign_key(None, 'User_stack', 'User', ['user_id'], ['id'])
    op.create_foreign_key(None, 'User_stack', 'Stack', ['stack_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User_stack', 'stack_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('User_stack', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('User_stack', 'status')
    op.alter_column('User_language', 'language_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('User_language', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('User_language', 'status')
    op.alter_column('User', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('User', 'status')
    op.alter_column('Stack', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('Stack', 'status')
    op.alter_column('Project', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('Project', 'status')
    op.alter_column('Language', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('Language', 'status')
    op.alter_column('Contact', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('Contact', 'status')
    # ### end Alembic commands ###
