"""phone_number_user

Revision ID: f226b290b2ce
Revises: cb7876c4c2a3
Create Date: 2026-02-25 18:10:10.133604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f226b290b2ce'
down_revision: Union[str, Sequence[str], None] = 'cb7876c4c2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'phone_number')
    # ### end Alembic commands ###
